import { FIELD_LABEL_LOOKUP } from "../data/fields";
import {
  bivariate,
  cvAuroc,
  holdoutAuroc,
  overlapData,
  shapTop,
} from "../data/spectrum-data";
import type {
  PatientFormValues,
  PredictionResult,
  Recommendation,
} from "../types";
import { riskTier } from "./advice-engine";
import type { SensitivityBand } from "./sensitivity";
import { buildWaterfallSteps } from "./waterfall";

function escapeHtml(str: unknown): string {
  return String(str).replace(
    /[&<>"']/g,
    (c) =>
      ({
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;",
        '"': "&quot;",
        "'": "&#39;",
      })[c] ?? c,
  );
}

function reportId(now: Date): string {
  const p = (n: number) => String(n).padStart(2, "0");
  return `${now.getFullYear()}${p(now.getMonth() + 1)}${p(now.getDate())}-${p(now.getHours())}${p(now.getMinutes())}${p(now.getSeconds())}`;
}

function reportShell(
  kicker: string,
  docTitle: string,
  heading: string,
  meta: string,
  bodyHtml: string,
): string {
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${escapeHtml(docTitle)}</title>
  <style>
    body{font-family: Georgia, 'Times New Roman', serif; color:#1F3436; background:#F5F9F9; margin:0; padding:40px;}
    .header{background:#0F3A3C; color:#fff; padding:28px 32px; border-radius:12px;}
    .kicker{font-family: system-ui, sans-serif; font-size:11px; letter-spacing:2px; color:#02C39A; font-weight:700;}
    h1{font-size:26px; margin:6px 0 0;}
    .meta{font-family: system-ui, sans-serif; font-size:12px; color:#CBE0DE; margin-top:8px;}
    .box{background:#fff; border:1px solid #DCEAE9; border-radius:12px; padding:24px; margin-top:20px;}
    .risk-num{font-size:44px; font-weight:700;}
    .tier{display:inline-block; font-family: system-ui, sans-serif; font-size:12px; font-weight:700; padding:4px 12px; border-radius:20px; margin-left:12px;}
    table{width:100%; border-collapse:collapse; margin-top:10px; font-family: system-ui, sans-serif; font-size:13px;}
    td,th{padding:8px 6px; border-bottom:1px solid #EEF4F3; text-align:left;}
    th{color:#028090; font-size:11.5px; text-transform:uppercase; letter-spacing:0.5px;}
    td:first-child{color:#5B7472;}
    h2{font-family: system-ui, sans-serif; font-size:15px; color:#028090; margin:0 0 4px;}
    .disclaimer{margin-top:22px; font-family: system-ui, sans-serif; font-size:11.5px; color:#5B7472; background:#EAF3F2; padding:14px 18px; border-radius:10px; line-height:1.5;}
    .wf{margin-top:12px; font-family: system-ui, sans-serif;}
    .wf-row{display:flex; align-items:center; gap:10px; margin-bottom:6px;}
    .wf-label{width:140px; font-size:11.5px; color:#5B7472; text-align:right; flex-shrink:0;}
    .wf-track{flex:1; height:13px; background:#EEF4F3; border-radius:4px; position:relative;}
    .wf-bar{position:absolute; top:0; height:13px; border-radius:3px; -webkit-print-color-adjust:exact; print-color-adjust:exact;}
    .wf-val{width:130px; font-size:11px; font-weight:600; flex-shrink:0;}
    @media print { body{background:#fff;} .box{border:none;} .wf-track{border:1px solid #EEF4F3;} }
  </style></head><body>
    <div class="header">
      <div class="kicker">${escapeHtml(kicker)}</div>
      <h1>${escapeHtml(heading)}</h1>
      <div class="meta">${meta}</div>
    </div>
    ${bodyHtml}
    <div class="disclaimer">
      <strong>About this report:</strong> Generated by PRISM, an explainable risk assessment tool. Contributing factors are estimated using a lightweight, real-time approximation method. PRISM is a research and demonstration tool and is NOT YET validated for clinical use or real patient decision-making.
    </div>
  </body></html>`;
}

export function buildPatientReportHTML(
  form: PatientFormValues,
  result: PredictionResult,
  recs: Recommendation,
  band?: SensitivityBand,
  patientId?: string,
): string {
  const tier = riskTier(result.probability);
  const now = new Date();
  const timestamp = now.toLocaleString();
  const id = reportId(now);

  const inputRows = Object.entries(form)
    .map(([k, v]) => {
      const label = FIELD_LABEL_LOOKUP[k] ?? k;
      return `<tr><td>${escapeHtml(label)}</td><td>${escapeHtml(v)}</td></tr>`;
    })
    .join("");

  const factorRows = result.ranked
    .slice(0, 8)
    .map((t) => {
      const dir = t.value > 0 ? "Increases risk" : "Decreases risk";
      const color = t.value > 0 ? "#C4432B" : "#00A896";
      return `<tr><td>${escapeHtml(t.name)}</td><td style="color:${color};font-weight:600;">${dir}</td></tr>`;
    })
    .join("");

  const recItems = recs.items
    .map(
      (it) =>
        `<li><strong>${escapeHtml(it.factor)}:</strong> ${escapeHtml(it.advice)}</li>`,
    )
    .join("");

  const steps = buildWaterfallSteps(result);
  const wfColors = { anchor: "#0F3A3C", up: "#C4432B", down: "#00A896" };
  const wfScale =
    Math.max(...steps.map((s) => Math.max(s.from, s.to)), 0.01) * 1.08;
  const waterfallRows = steps
    .map((s) => {
      const left = (Math.min(s.from, s.to) / wfScale) * 100;
      const width = Math.max((Math.abs(s.to - s.from) / wfScale) * 100, 0.8);
      const deltaPts = (s.to - s.from) * 100;
      const value =
        s.kind === "anchor"
          ? `<span style="color:#1F3436;">${(s.to * 100).toFixed(1)}%</span>`
          : `<span style="color:${wfColors[s.kind]};">${deltaPts >= 0 ? "+" : ""}${deltaPts.toFixed(1)} pts &rarr; ${(s.to * 100).toFixed(1)}%</span>`;
      return `<div class="wf-row">
        <div class="wf-label">${escapeHtml(s.name)}</div>
        <div class="wf-track"><div class="wf-bar" style="left:${left.toFixed(2)}%;width:${width.toFixed(2)}%;background:${wfColors[s.kind]};"></div></div>
        <div class="wf-val">${value}</div>
      </div>`;
    })
    .join("");

  const body = `
    <div class="box">
      <div class="kicker" style="color:#5B7472;">PREDICTED MORTALITY RISK</div>
      <span class="risk-num" style="color:${tier.colorVar}">${(result.probability * 100).toFixed(1)}%</span>
      <span class="tier" style="background:color-mix(in srgb, ${tier.colorVar} 15%, white); color:${tier.colorVar};">${tier.label} risk</span>
      ${band ? `<p style="font-family: system-ui, sans-serif; font-size:12px; color:#5B7472; margin:8px 0 0;">Sensitivity: ${(band.low * 100).toFixed(1)}%&ndash;${(band.high * 100).toFixed(1)}% under &plusmn;5% input variation &mdash; not a confidence interval.</p>` : ""}
      <h2 style="margin-top:22px;">Top Contributing Factors</h2>
      <table><thead><tr><th>Factor</th><th>Direction</th></tr></thead><tbody>${factorRows}</tbody></table>
      <h2 style="margin-top:22px;">How the Estimate Was Built</h2>
      <div class="wf">${waterfallRows}</div>
      <p style="font-family: system-ui, sans-serif; font-size:11px; color:#5B7472;">Starting from a typical cohort patient (median inputs), each factor shows how this patient differs. Steps are shown in probability space for readability; the model combines factors on the log-odds scale, so step sizes depend on their order (largest contributions first).</p>
      <h2 style="margin-top:22px;">Suggested Next Steps</h2>
      <p style="font-family: system-ui, sans-serif; font-size:13px; background:#EAF3F2; padding:12px 14px; border-radius:8px;">${escapeHtml(recs.summary)}</p>
      ${recItems ? `<ul style="font-family: system-ui, sans-serif; font-size:12.5px; color:#5B7472; line-height:1.6;">${recItems}</ul>` : ""}
      <p style="font-family: system-ui, sans-serif; font-size:11px; color:#C4432B; font-weight:700;">Educational output only \u2014 not clinical advice. All care decisions must be made by qualified clinicians using full clinical judgment and context.</p>
      <h2 style="margin-top:22px;">Patient Input Values</h2>
      <table><thead><tr><th>Field</th><th>Value</th></tr></thead><tbody>${inputRows}</tbody></table>
    </div>`;

  const patientMeta = patientId ? `Patient: ${escapeHtml(patientId)} · ` : "";
  const docTitle = patientId
    ? `#${id}_Risk Report · ${patientId}_PRISM`
    : `#${id}_Risk Report_PRISM`;

  return reportShell(
    "PRISM · CLINICAL DECISION SUPPORT",
    docTitle,
    "Risk Report",
    `${patientMeta}Generated ${escapeHtml(timestamp)} · Report ID: ${id}`,
    body,
  );
}

export function buildDashboardReportHTML(): string {
  const now = new Date();
  const timestamp = now.toLocaleString();
  const id = reportId(now);
  const rowify = <T>(arr: T[], cols: ((d: T) => string)[]) =>
    arr
      .map(
        (d) =>
          `<tr>${cols.map((c) => `<td>${escapeHtml(c(d))}</td>`).join("")}</tr>`,
      )
      .join("");

  const holdoutRows = rowify(holdoutAuroc, [
    (d) => d.name.replace("\n", " "),
    (d) => d.value.toFixed(3),
  ]);
  const cvRows = rowify(cvAuroc, [
    (d) => d.name.replace("\n", " "),
    (d) => `${d.value.toFixed(3)} \u00b1 ${d.sd.toFixed(3)}`,
  ]);
  const shapRows = rowify(shapTop, [(d) => d.name, (d) => d.value.toFixed(3)]);
  const overlapRows = rowify(overlapData, [(d) => d.pair, (d) => d.frac]);
  const bivRows = rowify(bivariate, [(d) => d.label, (d) => d.p]);

  const body = `
    <div class="box">
      <h2>Cohort</h2>
      <table><tbody>
        <tr><td>ICU stays analyzed</td><td>98</td></tr>
        <tr><td>In-hospital deaths</td><td>10 (10.2%)</td></tr>
        <tr><td>Model input features</td><td>59 (after encoding)</td></tr>
      </tbody></table>
      <h2 style="margin-top:20px;">Held-Out Test AUROC</h2>
      <table><thead><tr><th>Model</th><th>AUROC</th></tr></thead><tbody>${holdoutRows}</tbody></table>
      <h2 style="margin-top:20px;">5-Fold Cross-Validated AUROC (mean \u00b1 SD)</h2>
      <table><thead><tr><th>Model</th><th>AUROC</th></tr></thead><tbody>${cvRows}</tbody></table>
      <h2 style="margin-top:20px;">Top-5 SHAP Features</h2>
      <table><thead><tr><th>Feature</th><th>Mean |SHAP value|</th></tr></thead><tbody>${shapRows}</tbody></table>
      <h2 style="margin-top:20px;">Cross-Method Explanation Agreement</h2>
      <table><thead><tr><th>Method pair</th><th>Top-5 overlap</th></tr></thead><tbody>${overlapRows}</tbody></table>
      <h2 style="margin-top:20px;">Significant Associations</h2>
      <table><thead><tr><th>Variable</th><th>p-value</th></tr></thead><tbody>${bivRows}</tbody></table>
    </div>`;

  return reportShell(
    "PRISM · CLINICAL DECISION SUPPORT",
    `#${id}_Performance Summary_PRISM`,
    "Performance Summary",
    `Generated ${escapeHtml(timestamp)} · Report ID: ${id}`,
    body,
  );
}
